apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.serviceName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Release.Name }}-express-app